run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/todo-app/services/admin-service
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goconst
    - gocyclo
    - misspell
    - lll
    - gocritic
    - gosec
  disable:
    - deadcode  # deprecated
    - varcheck  # deprecated
    - structcheck # deprecated

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll
    # Ignore long lines in generated protobuf files
    - path: \.pb\.go
      linters:
        - lll
        - gocritic
    # Ignore complexity in main.go (server setup is inherently complex)
    - path: cmd/server/main\.go
      linters:
        - gocyclo

severity:
  default-severity: error